language: "node_js"
node_js:
  - "0.10"
  - "0.11"
before_install:
  - "sudo mkdir -p /var/run/couchdb"
  - "npm install -g npm@^2"
#  - "npm install -g couchapp"
env:
  - DEPLOY_VERSION=testing
script: "npm test"
