language: "node_js"
node_js:
  - "0.10"
before_install:
  - "cat test/fixtures/couch.ini"
  - "couchdb -a test/fixtures/couch.ini || cat erl_crash.dump"
  - "npm install -g npm@1.4.21"
  - "npm --version"
  - "npm install -g couchapp"
  - "sleep 5"
  - "curl -X GET http://127.0.0.1:5984/"
  - "curl -X PUT http://127.0.0.1:5984/_config/log/level -d '\"debug\"'"
env:
  - TAP_TIMEOUT 100
after_failure:
  - "curl -X GET http://127.0.0.1:5984/_log?bytes=1000000"
script: "npm test"
