language: "node_js"
node_js:
  - "0.10"
  - "0.11"
before_install:
  - "sudo mkdir -p /var/run/couchdb"
  #- "sudo chown -R couchdb /var/run/couchdb"
  - "npm install -g couchapp"
  #- "sleep 5"
env:
  - DEPLOY_VERSION=testing
script: "npm test"
