language: "node_js"
node_js:
  - "0.10"
before_install:
  - "cat test/fixtures/couch.ini"
  - "sudo mkdir -p /var/run/couchdb"
  - "sudo chown -R couchdb /var/run/couchdb"
  - "sudo couchdb -a test/fixtures/couch.ini &"
  - "which npm"
  - "npm install -g npm@^2"
  - "which npm"
  - "npm --version"
  - "npm install -g couchapp"
  - "curl -X GET http://127.0.0.1:15986/"
  - "curl -X GET http://localhost:15986/"
  - "curl -X PUT http://127.0.0.1:15986/_config/log/level -d '\"debug\"'"
env:
  - TAP_TIMEOUT=100 DEPLOY_VERSION=testing
after_failure:
  - "curl -X GET http://127.0.0.1:15986/_log?bytes=1000000"
script: "npm test"
