language: "node_js"
node_js:
  - "0.10"
before_install:
  - "couchdb -a test/fixtures/couch.ini"
  - "npm install -g npm@1.4.21"
  - "npm --version"
  - "npm install -g couchapp"
env:
  - TAP_TIMEOUT 100
script: "npm test"
